/**
 * Framework-free unit tests for SmartIR YAML preview generator.
 *
 * Run with: npm test
 * (or: node test/yamlGenerator.test.mjs)
 *
 * No test framework dependency — uses node:assert only.
 */

import { strict as assert } from 'node:assert'
import { test } from 'node:test'
import { generateYamlConfig } from '../src/components/smartir/yamlGenerator.js'

const BASE_PROFILE = {
  manufacturer: 'Acme Corp',
  model: 'Model X',
  broadlinkDevice: 'remote.broadlink_rm4_pro',
  config: {},
}

function profileFor(platform, config = {}) {
  return { ...BASE_PROFILE, platform, config: { ...config } }
}

test('emits header comments for every platform', () => {
  for (const platform of ['climate', 'fan', 'media_player', 'light']) {
    const yaml = generateYamlConfig(profileFor(platform))
    assert.ok(yaml.startsWith(`# SmartIR ${platform} configuration\n`), `${platform} header`)
    assert.ok(yaml.includes('# Generated by Broadlink Manager v2'), `${platform} generator comment`)
  }
})

test('emits common SmartIR fields for non-climate platforms (regression for issue #46)', () => {
  for (const platform of ['fan', 'media_player', 'light']) {
    const yaml = generateYamlConfig(profileFor(platform))
    assert.ok(yaml.includes(`${platform}:\n`), `${platform}: top-level key present`)
    assert.ok(yaml.includes('  - platform: smartir'), `${platform}: platform: smartir`)
    assert.ok(yaml.includes('name: Acme Corp Model X'), `${platform}: name`)
    assert.ok(yaml.includes('unique_id: acme corp_model_x'), `${platform}: unique_id`)
    assert.ok(yaml.includes('device_code: 10000'), `${platform}: device_code`)
    assert.ok(yaml.includes('controller_data: remote.broadlink_rm4_pro'), `${platform}: controller_data`)
  }
})

test('does not emit climate-only sensor fields for non-climate platforms', () => {
  for (const platform of ['fan', 'media_player', 'light']) {
    const yaml = generateYamlConfig(profileFor(platform, {
      tempSensor: 'sensor.temp',
      humiditySensor: 'sensor.humidity',
      powerSensor: 'sensor.power',
    }))
    assert.ok(!yaml.includes('temperature_sensor'), `${platform}: no temperature_sensor`)
    assert.ok(!yaml.includes('humidity_sensor'), `${platform}: no humidity_sensor`)
    assert.ok(!yaml.includes('power_sensor'), `${platform}: no power_sensor`)
  }
})

test('emits climate sensor fields when provided', () => {
  const yaml = generateYamlConfig(profileFor('climate', {
    tempSensor: 'sensor.temp',
    humiditySensor: 'sensor.humidity',
    powerSensor: 'sensor.power',
  }))
  assert.ok(yaml.includes('temperature_sensor: sensor.temp'))
  assert.ok(yaml.includes('humidity_sensor: sensor.humidity'))
  assert.ok(yaml.includes('power_sensor: sensor.power'))
})

test('omits climate sensor fields when not provided', () => {
  const yaml = generateYamlConfig(profileFor('climate', {}))
  assert.ok(!yaml.includes('temperature_sensor'))
  assert.ok(!yaml.includes('humidity_sensor'))
  assert.ok(!yaml.includes('power_sensor'))
})

test('handles missing config object gracefully', () => {
  const yaml = generateYamlConfig({ ...BASE_PROFILE, platform: 'climate' })
  assert.ok(yaml.includes('climate:\n'))
  assert.ok(!yaml.includes('temperature_sensor'))
})

test('slugifies model whitespace in unique_id with underscores', () => {
  // Note: only the model is slugified in the current implementation;
  // manufacturer whitespace is preserved. This test pins current behavior.
  const yaml = generateYamlConfig({
    ...BASE_PROFILE,
    manufacturer: 'LG Electronics',
    model: 'Art Cool 9000',
    platform: 'climate',
    config: {},
  })
  assert.ok(yaml.includes('unique_id: lg electronics_art_cool_9000'))
})
