/**
 * SmartIR YAML configuration generator.
 *
 * Extracted as a pure module so it can be unit tested without a Vue runtime.
 * Used by SmartIRProfileBuilder.vue.
 */

/**
 * Generate a SmartIR platform YAML configuration string for a profile.
 *
 * Common fields (platform, name, unique_id, device_code, controller_data)
 * apply to all supported SmartIR platforms (climate, fan, media_player, light).
 * Climate-specific sensor fields are only emitted for the climate platform.
 *
 * @param {Object} profile - Profile object.
 * @param {string} profile.platform - SmartIR platform (climate|fan|media_player|light).
 * @param {string} profile.manufacturer - Device manufacturer.
 * @param {string} profile.model - Device model.
 * @param {string} profile.broadlinkDevice - Broadlink controller entity id.
 * @param {Object} [profile.config] - Optional platform-specific config
 *   (tempSensor/humiditySensor/powerSensor for climate).
 * @returns {string} YAML configuration text.
 */
export function generateYamlConfig(profile) {
  let yaml = `# SmartIR ${profile.platform} configuration\n`
  yaml += `# Generated by Broadlink Manager v2\n\n`

  yaml += `${profile.platform}:\n`
  yaml += `  - platform: smartir\n`
  yaml += `    name: ${profile.manufacturer} ${profile.model}\n`
  yaml += `    unique_id: ${profile.manufacturer.toLowerCase()}_${profile.model.toLowerCase().replace(/\s+/g, '_')}\n`
  yaml += `    device_code: 10000  # Change this to your custom code number\n`
  yaml += `    controller_data: ${profile.broadlinkDevice}\n`

  if (profile.platform === 'climate') {
    if (profile.config && profile.config.tempSensor) {
      yaml += `    temperature_sensor: ${profile.config.tempSensor}\n`
    }
    if (profile.config && profile.config.humiditySensor) {
      yaml += `    humidity_sensor: ${profile.config.humiditySensor}\n`
    }
    if (profile.config && profile.config.powerSensor) {
      yaml += `    power_sensor: ${profile.config.powerSensor}\n`
    }
  }

  return yaml
}
