name: Test Command Workflows

on:
  push:
    branches: [main, develop, release/**]
    paths:
      - 'app/api/commands.py'
      - 'app/api/smartir.py'
      - 'app/web_server.py'
      - 'tests/integration/test_command_workflows.py'
      - '.github/workflows/test-command-workflows.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'app/api/commands.py'
      - 'app/api/smartir.py'
      - 'app/web_server.py'
      - 'tests/integration/test_command_workflows.py'

jobs:
  test-workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Run command workflow tests
        run: |
          pytest tests/integration/test_command_workflows.py -v --tb=short

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            .pytest_cache/
            htmlcov/
